<?php
$isEnabled = $block->isEnabled();
$popupWidth = $block->getPopupWidth() ? $block->getPopupWidth()."px" : "800px";
$popupHeight = $block->getPopupHeight() ? $block->getPopupHeight()."px" : "500px";
$popupHeading = $block->getPopupHeading();
$popupMessage = $block->getPopupMessage();
$popupContentType = $block->getPopupContentType();
$popupCmsBlock = $block->getPopupCmsBlock();
$isFooterEnabled = $block->isFooterEnabled();
$buttonBgColor = $block->getButtonBgColor();
$buttonFontColor = $block->getButtonFontColor();
$button1Text = $block->getButton1Text();
$button2Text = $block->getButton2Text();
$imageUrl = $block->getImageUrl();
$isShowNewsletter = $block->getShowNewsletter();
$newsletterFontColor = $block->getNewsletterFontColor() ? "#".$block->getNewsletterFontColor() : '#ffffff';
$newsletterButtonColor = $block->getNewsletterButtonColor() ? "#".$block->getNewsletterButtonColor() : '#1979c3';
$newsletterPlaceholder = $block->getNewsletterPlaceholder() ? $block->getNewsletterPlaceholder() : 'Enter your email address';
$newsletterLabelText = $block->getNewsletterLabelText() ? $block->getNewsletterLabelText() : 'Sign Up for Our Newsletter:';
$newsletterButtonText = $block->getNewsletterButtonText() ? $block->getNewsletterButtonText() : 'Subscribe';
?>
<?php if ($isEnabled): ?>
<div id="newsletter-model" style="display:none;">
    <div class="popup_message">
        <?php if ($popupContentType == 'custom'): ?>
            <?php if ($popupHeading): ?>
        <div id="popup-heading">
                <?= $block->escapeHtml($popupHeading); ?>
        </div>
        <?php endif; ?>
            <?php if ($popupMessage): ?>
        <div id="popup-form-content">
            <div id="popup-text">
                <?= /* @noEscape */ $block->getWyswingContent($popupMessage); ?>
            </div>
        </div>
        <?php endif; ?>
        <?php endif; ?>
        <?php if ($popupContentType == "image_upload"): ?>
            <?php if ($isShowNewsletter): ?>
            <div class="fullmage-block newsletter">
                <div class="fullmage-content">
                    <form class="form subscribe"
                        novalidate
                        action="<?= $block->escapeUrl($block->getFormActionUrl()) ?>"
                        method="post"
                        data-mage-init='{"validation": {"errorClass": "mage-error"}}'
                        id="fullmage-newsletter-validate-detail">
                        <div class="field newsletter">
                            <div class="control">
                                <label for="newsletter">
                                    <span class="label">
                                        <?= $block->escapeHtml(__($newsletterLabelText)) ?>
                                    </span>
                                    <input name="email" type="email" id="newsletter"
                                           placeholder="<?= $block->escapeHtml(__($newsletterPlaceholder)) ?>"
                                           data-mage-init='{"mage/trim-input":{}}'
                                           data-validate="{required:true, 'validate-email':true}"
                                    />
                                </label>
                            </div>
                        </div>
                        <div class="actions">
                            <button class="action popup-subscribe primary"
                                    title="<?= $block->escapeHtmlAttr(__($newsletterButtonText)) ?>"
                                    type="submit"
                                    aria-label="Subscribe">
                                <span><?= $block->escapeHtml(__($newsletterButtonText)) ?></span>
                            </button>
                        </div>
                    </form>
                </div>
            </div>
            <?php endif; ?>
        <?php endif; ?>
        <?php if ($popupContentType == "cms_block"): ?>
        <div id="popup-form-content">
            <?= $block->getLayout()->createBlock(\Magento\Cms\Block\Block::class)
            ->setBlockId($block->getCmsBlock($popupCmsBlock)->getIdentifier())->toHtml(); ?>
        </div>
        <?php endif; ?>
    </div>
</div>
<?php endif; ?>
<script type="text/x-magento-init">
{
    "*": {
        "FullMage_Popup/js/modal_popup": {
            "isEnabled": "<?= /* @noEscape */ $isEnabled ?>",
            "isFooterEnabled": "<?= /* @noEscape */ $isFooterEnabled ?>",
            "buttonBgColor": "<?= /* @noEscape */ $buttonBgColor ?>",
            "buttonFontColor": "<?= /* @noEscape */ $buttonFontColor ?>",
            "button1Text": "<?= /* @noEscape */ $button1Text ?>"
        }
    }
}
</script>
<?php if ($isShowNewsletter): ?>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Customer/js/block-submit-on-send": {
                "formId": "fullmage-newsletter-validate-detail"
            }
        }
    }
</script>
<?php endif; ?>
<style type="text/css">
.modal-popup.fullmage-popup .modal-inner-wrap {
    top: 50%;
    transform: translateY(-50%);
    margin: 0 auto;
    max-width: <?= /* @noEscape */ $popupWidth; ?>;
    background-image: url(<?= /* @noEscape */ $block->getImageUrl(); ?>);
    height: <?= /* @noEscape */ $popupHeight; ?>;
    max-height: 90%;
    background-repeat: no-repeat;
    background-size: cover;
    position: relative;
}
.modal-popup.fullmage-popup .action-close {
    background: #333;
    margin: 0;
    padding: 1rem 1.2rem;
    border-radius: 0;
    color: #fff;
}
.modal-popup.fullmage-popup .action-close:before {
    color: #fff;
}
#newsletter-model {
    transform: translateX(-50%);
    display: block;
    margin: 0 auto;
    max-width: 300px;
    position: absolute;
    bottom: 20%;
    left: 50%;
}
.fullmage-content .form.subscribe {
    max-width: 400px;
    min-width: 300px;
}
.fullmage-content .form.subscribe .label {
    font-size: 2rem;
    text-align: center;
    margin: 0 auto 20px;
    display: block;
    font-weight: bold;
    
}
.fullmage-content .form.subscribe #newsletter {
    margin-bottom: 12px;
}
.fullmage-content .action.subscribe.primary {
    width: 100%;
    text-align: center;
}
.fullmage-popup .modal-content::-webkit-scrollbar {
  width: 5px;
}
.fullmage-popup .modal-content::-webkit-scrollbar-track {
  box-shadow: inset 0 0 1px grey; 
  border-radius: 2px;
  background: #ddd;
}
.fullmage-popup .modal-content::-webkit-scrollbar-thumb {
  background: #666; 
  border-radius: 2px;
}
.fullmage-popup .modal-content::-webkit-scrollbar-thumb:hover {
  background: #666; 
}
.fullmage-popup .action.popup-subscribe {
    background: <?= /* @noEscape */ $newsletterButtonColor; ?>;
    border: 1px solid <?= /* @noEscape */ $newsletterButtonColor; ?>;
    margin: 0 auto;
    display: block;
}
@media only screen and (max-width: 480px) {
    .fullmage-popup.modal-slide {
        width: 95%;
        left: auto;
        right: 0;
    }
    .fullmage-popup .modal-content {
        padding-left: 1.5rem;
        padding-right: 1.5rem;
    }
    .fullmage-popup .modal-content ul {
        padding-left: 2.5rem;
    }
}
</style>