<?php
/**
 * @var $block \FullMage\Popup\Block\Popup
 * @var $viewModel \FullMage\Popup\ViewModel\PopUpConfig
 */
$viewModel = $block->getViewModel();
$configHelper = $viewModel->getConfig();
$popupContentType = $configHelper->getPopupContentType();
$popupWhereToShow = $configHelper->getPopupWhereToShow();
$imagePath = "none";
$newsletterCls = "";
if ($popupContentType == 'newsletter_sign_up') {
    $imagePath = $block->getImageUrl();
}
?>
<?php if ($configHelper->isEnabled()): ?>
    <?php if (($popupWhereToShow == "homepage" && $block->getFullActionName() === "cms_index_index")
        || ($popupWhereToShow == "allpage")): ?>
        <?php if ($configHelper->getShowNewsletter() && $popupContentType == "newsletter_sign_up"): ?>
    <div id="newsletter-model" class="newsletter-form" style="display:none;">
    <?php else: ?>
    <div id="newsletter-model" style="display:none;">
    <?php endif; ?>
    <div class="popup_message">
        <?php if ($popupContentType == 'custom'): ?>
            <?php if (!empty($configHelper->getPopupHeading())): ?>
            <div id="popup-heading" class="popup-heading">
                <?= /* @noEscape */ $block->getWyswingContent($configHelper->getPopupHeading()); ?>
            </div>
            <?php endif; ?>
            <?php if (!empty($configHelper->getPopupMessage())): ?>
            <div id="popup-form-content" class="popup-form-content">
                <div id="popup-text">
                    <?= /* @noEscape */ $block->getWyswingContent($configHelper->getPopupMessage()); ?>
                </div>
            </div>
            <?php endif; ?>
        <?php endif; ?>
        <?php if ($popupContentType == "newsletter_sign_up"): ?>
            <?php if ($configHelper->getShowNewsletter()): ?>
            <div class="fullmage-block newsletter">
                <div class="fullmage-content">
                    <form class="form subscribe"
                        novalidate
                        action="<?= $block->escapeUrl($block->getFormActionUrl()) ?>"
                        method="post"
                        data-mage-init='{"validation": {"errorClass": "mage-error"}}'
                        id="fullmage-newsletter-validate-detail">
                        <div class="field newsletter">
                            <div class="control">
                                <label for="newsletter">
                                    <span class="label">
                                        <?= $block->escapeHtml(__($configHelper->getNewsletterLabelText())) ?>
                                    </span>
                                    <input name="email" type="email" id="newsletter"
                                       placeholder="<?= $block->escapeHtml($configHelper->getNewsletterPlaceholder())?>"
                                       data-mage-init='{"mage/trim-input":{}}'
                                       data-validate="{required:true, 'validate-email':true}"
                                    />
                                </label>
                            </div>
                        </div>
                        <div class="actions">
                            <button class="action popup-subscribe primary"
                                    title="<?= $block->escapeHtmlAttr(__($configHelper->getNewsletterButtonText())) ?>"
                                    type="submit"
                                    aria-label="Subscribe">
                                <span><?= $block->escapeHtml(__($configHelper->getNewsletterButtonText())) ?></span>
                            </button>
                        </div>
                    </form>
                </div>
            </div>
            <?php endif; ?>
        <?php endif; ?>
        <?php if ($popupContentType == "cms_block"): ?>
        <div id="popup-form-content">
            <?= $block->getLayout()->createBlock(\Magento\Cms\Block\Block::class)
            ->setBlockId($block->getCmsBlock($configHelper->getPopupCmsBlock())
                ->getIdentifier())->toHtml(); ?>
        </div>
        <?php endif; ?>
    </div>
</div>
    <?php endif; ?>
<?php endif; ?>
<script type="text/x-magento-init">
{
    "*": {
        "FullMage_Popup/js/modal_popup": {
            "isEnabled": "<?= $block->escapeJs($configHelper->isEnabled()) ?>",
            "setcontent": "<?= $block->escapeJs($configHelper->getPopupContentType()) ?>",
            "isFooterEnabled": "<?= $block->escapeJs($configHelper->isFooterEnabled()) ?>",
            "buttonBgColor": "<?= /* @noEscape */ $configHelper->getButtonBgColor() ?>",
            "buttonFontColor": "<?= /* @noEscape */ $configHelper->getButtonFontColor() ?>",
            "buttonText": "<?= $block->escapeJs(
                empty($configHelper->getButtonText())?$configHelper->getButtonText():__('Close')
            ) ?>",
            "popupShowTime": "<?= $block->escapeJs($configHelper->getPopupShowTime()) ?>",
            "popupCookieExp": "<?= $block->escapeJs($configHelper->getPopupCookieExpire()) ?>"
        }
    }
}
</script>
<?php if ($configHelper->getShowNewsletter()): ?>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Customer/js/block-submit-on-send": {
                "formId": "fullmage-newsletter-validate-detail"
            }
        }
    }
</script>
<?php endif; ?>
<style type="text/css">
.modal-popup.fullmage-popup .modal-inner-wrap {
    top: 50%;
    transform: translateY(-50%);
    margin: 0 auto;
    max-width: <?= /* @noEscape */ $configHelper->getPopupWidth(); ?>;
    background-image: url(<?= /* @noEscape */ $imagePath; ?>);
    height: <?= /* @noEscape */ $configHelper->getPopupWidth(); ?>;
    max-height: 90%;
    background-repeat: no-repeat;
    background-size: cover;
    position: relative;
}
.modal-popup.fullmage-popup .action-close {
    background: #333;
    margin: 0;
    padding: 1rem 1.2rem;
    border-radius: 0;
    color: #fff;
}
.modal-popup.fullmage-popup .action-close:before {
    color: #fff;
}
.modal-popup.fullmage-popup .modal-footer .fullmage-popup-btn-action
{
    background: <?= /* @noEscape */ $configHelper->getButtonBgColor(); ?>;
    color: <?= /* @noEscape */ $configHelper->getButtonFontColor() ?>;
    border: 1px solid <?= /* @noEscape */ $configHelper->getButtonBgColor(); ?>;
}
.newsletter-form {
    transform: translateX(-50%);
    display: block;
    margin: 0 auto;
    max-width: 300px;
    position: absolute;
    bottom: 20%;
    left: 50%;
}
.popup-heading {
    margin-bottom: 5%;
}
.fullmage-content .form.subscribe {
    max-width: 400px;
    min-width: 300px;
}
.fullmage-content .form.subscribe .label {
    font-size: 2rem;
    text-align: center;
    margin: 0 auto 20px;
    display: block;
    font-weight: bold;

}
.fullmage-content .form.subscribe #newsletter {
    margin-bottom: 12px;
}
.fullmage-content .action.subscribe.primary {
    width: 100%;
    text-align: center;
}
.fullmage-popup .modal-content::-webkit-scrollbar {
  width: 5px;
}
.fullmage-popup .modal-content::-webkit-scrollbar-track {
  box-shadow: inset 0 0 1px grey;
  border-radius: 2px;
  background: #ddd;
}
.fullmage-popup .modal-content::-webkit-scrollbar-thumb {
  background: #666;
  border-radius: 2px;
}
.fullmage-popup .modal-content::-webkit-scrollbar-thumb:hover {
  background: #666;
}
.fullmage-popup .action.popup-subscribe {
    background: <?= /* @noEscape */ $configHelper->getNewsletterButtonColor(); ?>;
    border: 1px solid <?= /* @noEscape */ $configHelper->getNewsletterButtonColor();
    ; ?>;
    margin: 0 auto;
    display: block;
}
@media only screen and (max-width: 480px) {
    .fullmage-popup.modal-slide {
        width: 95%;
        left: auto;
        right: 0;
    }
    .fullmage-popup .modal-content {
        padding-left: 1.5rem;
        padding-right: 1.5rem;
    }
    .fullmage-popup .modal-content ul {
        padding-left: 2.5rem;
    }
}
</style>
