<?php
$isEnabled = $block->isEnabled();
$popupHeading = $block->getPopupHeading();
$popupMessage = $block->getPopupMessage();
$popupContentType = $block->getPopupContentType();
$popupCmsBlock = $block->getPopupCmsBlock();
$isFooterEnabled = $block->isFooterEnabled();
?>
<?php if ($isEnabled): ?>
<div id="newsletter-model" style="display:none;">
    <div class="popup_message">
        <?php if ($popupContentType == 'custom'): ?>
            <?php if ($popupHeading): ?>
        <div id="popup-heading">
                <?= $popupHeading; ?>
        </div>
        <?php endif; ?>
            <?php if ($popupMessage): ?>
        <div id="popup-form-content">
            <div id="popup-text">
                <?= $block->getWyswingContent($popupMessage); ?>
            </div>
        </div>
        <?php endif; ?>
        <?php else: ?>
        <div id="popup-form-content">
            <?php echo $this->getLayout()->createBlock(\Magento\Cms\Block\Block::class)
            ->setBlockId($block->getCmsBlock($popupCmsBlock)->getIdentifier())->toHtml(); ?>
        </div>
        <?php endif; ?>
    </div>
</div>
<?php endif; ?>
<script type="text/x-magento-init">
{
    "*": {
        "FullMage_Popup/js/model_popup": {
            "isEnabled": <?= /* @escapeNotVerified */ $isEnabled ?>,
            "isFooterEnabled": <?= /* @escapeNotVerified */ $isFooterEnabled ?>
        }
    }
}
</script>
<style type="text/css">
    .modal-popup.fullmage-popup .modal-inner-wrap {
        top: 50%;
        transform: translateY(-50%);
        margin: 0 auto;
        max-width: 800px;
    }
    @media only screen and (max-width: 480px) {
        .fullmage-popup.modal-slide {
            width: 95%;
            left: auto;
            right: 0;
        }
        .fullmage-popup .modal-content {
            padding-left: 1.5rem;
            padding-right: 1.5rem;
        }
        .fullmage-popup .modal-content ul {
            padding-left: 2.5rem;
        }
    }
    .fullmage-popup .modal-content::-webkit-scrollbar {
      width: 5px;
    }
    .fullmage-popup .modal-content::-webkit-scrollbar-track {
      box-shadow: inset 0 0 1px grey; 
      border-radius: 2px;
      background: #ddd;
    }
    .fullmage-popup .modal-content::-webkit-scrollbar-thumb {
      background: #666; 
      border-radius: 2px;
    }
    .fullmage-popup .modal-content::-webkit-scrollbar-thumb:hover {
      background: #666; 
    }
</style>